title: Gecode
email: info@gecode.org
description: > # this means to ignore newlines until "baseurl:"
  The Gecode constraint solving library
#baseurl: "/~guidot/new_minizinc" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://s-cah-mwallace.infotech.monash.edu" # the base hostname & protocol for your site
includes_dir: _includes
data_dir: _data
collections:
    publications:
      output: true
    news:
      output: false
# Build settings
markdown: kramdown
theme: minima
sass:
    style: compressed
